name: Deploy static pages to Pages

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write      # Permissions to write to the GitHub Pages website
      id-token: write   # Permissions to get an OpenID Connect (OIDC) ID token
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install sphinx
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build documentation
        working-directory: gh_pages
        run: sphinx-build -b html . docs/build/html
        # Adjust source and build directories as needed (e.g., source/ build/html)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh_pages/docs/build/html # The directory containing the build files
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
