name: Build Windows Executable

on:
  push:
#    branches: [ main ]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: 'x64'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka pyodbc sqlparse textblob
    
    - name: Build Windows Executable
      shell: pwsh
      env:
        NUITKA_DEPENDENCY_WALKER: yes
      run: |
        python -m nuitka --assume-yes-for-downloads  --standalone --onefile --msvc=latest --enable-plugin=anti-bloat --output-dir=build --output-filename=scaffold_msaccess.exe scaffold_msaccess.py
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/scaffold_msaccess.exe
